name: First Workflow
on: workflow_dispatch # we can manually start if we use this <----
jobs:
  first-job: # not reversed name
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world!"
      - name: Print goodbye
        run: echo "Done bye!"
